sudo: false
dist: xenial   # required for Python >= 3.7
language: python
addons:
  apt:
    packages:
    - enchant
python:
- '3.7'
cache: pip
before_install:
- echo -e "Host docs.plone.org\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_129e1d4a0f4f_key -iv $encrypted_129e1d4a0f4f_iv
  -in deploy_key.enc -out $HOME/.ssh/id_rsa -d
install:
- pip install -q -r requirements.txt -c constraints.txt
stages:
  - test
  - build
  - deploy
jobs:
  include:
    - stage: test
      script: make test
    - stage: build
      script: make deploy
    - stage: deploy
      if: branch = master
      script: "./deploy.sh"
